extends: default
ignore: |
  NEO PROMPT V2/
  docs/lifecycle/1-research/
rules:
  line-length: {max: 140}
  document-start: {present: false}
  truthy: {allowed-values: ["true", "false", "on", "off", "yes", "no"]}
