name: Dev Image
on:
  push:
    branches: ["main"]
    paths: [".devcontainer/**"]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute lowercase repo for GHCR tag
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v5
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}/dev:latest
          provenance: true
          sbom: true
