name: Dev Image
on:
  push:
    branches: ["main"]
    paths: [".devcontainer/**"]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute lowercase repo for GHCR tag
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Resolve base image digest
        run: |
          BASE_IMAGE=python:3.12-slim-bookworm
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_ENV
          BASE_DIGEST=$(docker buildx imagetools inspect "$BASE_IMAGE" | awk '/Digest:/ {print $2; exit}')
          echo "BASE_DIGEST=$BASE_DIGEST" >> $GITHUB_ENV
      - uses: docker/build-push-action@v5
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}/dev:latest
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            BASE_DIGEST=${{ env.BASE_DIGEST }}
          provenance: true
          sbom: true
