name: Image Scan
on:
  workflow_run:
    workflows: [ "Dev Image" ]
    types: [ "completed" ]
permissions:
  contents: read
  packages: read
  security-events: write
jobs:
  scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Compute lowercase repo for GHCR tag
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Set IMAGE
        run: echo "IMAGE=ghcr.io/${REPO_LC}/dev:latest" >> $GITHUB_ENV
      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          vuln-type: 'os,library'
          exit-code: '1'
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
